PRAGMA foreign_keys=ON;
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE,hash TEXT,role TEXT NOT NULL CHECK(role IN ('student','teacher','admin')),demo INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,goal INTEGER NOT NULL DEFAULT 3);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,name TEXT NOT NULL,teacher_id TEXT NOT NULL REFERENCES users(id));
CREATE TABLE IF NOT EXISTS members(class_id TEXT REFERENCES classes(id),user_id TEXT REFERENCES users(id),PRIMARY KEY(class_id,user_id));
CREATE TABLE IF NOT EXISTS lessons(id TEXT PRIMARY KEY,title TEXT NOT NULL,subject TEXT NOT NULL,topic TEXT NOT NULL,minutes INTEGER NOT NULL,body TEXT NOT NULL,source TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS decks(id TEXT PRIMARY KEY,title TEXT NOT NULL,lesson_id TEXT REFERENCES lessons(id),owner_id TEXT REFERENCES users(id),class_id TEXT REFERENCES classes(id));
CREATE TABLE IF NOT EXISTS cards(id TEXT PRIMARY KEY,deck_id TEXT NOT NULL REFERENCES decks(id),front TEXT NOT NULL,back TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reviews(user_id TEXT REFERENCES users(id),card_id TEXT REFERENCES cards(id),due TEXT NOT NULL,interval INTEGER NOT NULL,confidence TEXT NOT NULL,repetitions INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(user_id,card_id));
CREATE TABLE IF NOT EXISTS quizzes(id TEXT PRIMARY KEY,title TEXT NOT NULL,lesson_id TEXT REFERENCES lessons(id),owner_id TEXT REFERENCES users(id),class_id TEXT REFERENCES classes(id));
CREATE TABLE IF NOT EXISTS questions(id TEXT PRIMARY KEY,quiz_id TEXT NOT NULL REFERENCES quizzes(id),prompt TEXT NOT NULL,options TEXT NOT NULL,answer INTEGER NOT NULL,explanation TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),quiz_id TEXT NOT NULL REFERENCES quizzes(id),answers TEXT NOT NULL,score INTEGER NOT NULL,total INTEGER NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,ref TEXT NOT NULL,title TEXT NOT NULL,xp INTEGER NOT NULL,created TEXT NOT NULL,UNIQUE(user_id,kind,ref));
CREATE TABLE IF NOT EXISTS resources(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id),class_id TEXT REFERENCES classes(id),title TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,approved INTEGER NOT NULL DEFAULT 1,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS assignments(id TEXT PRIMARY KEY,class_id TEXT NOT NULL REFERENCES classes(id),owner_id TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('lesson','quiz','deck')),ref TEXT NOT NULL,due TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notes(user_id TEXT REFERENCES users(id),lesson_id TEXT REFERENCES lessons(id),body TEXT NOT NULL,PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,sender_id TEXT NOT NULL REFERENCES users(id),recipient_id TEXT NOT NULL REFERENCES users(id),body TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_messages(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),lesson_id TEXT REFERENCES lessons(id),role TEXT NOT NULL,body TEXT NOT NULL,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_user_created ON events(user_id,created);
CREATE INDEX IF NOT EXISTS idx_attempts_user_created ON attempts(user_id,created);
CREATE INDEX IF NOT EXISTS idx_resources_class ON resources(class_id,approved);
CREATE INDEX IF NOT EXISTS idx_assignments_class ON assignments(class_id);
CREATE INDEX IF NOT EXISTS idx_members_user ON members(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires);
CREATE INDEX IF NOT EXISTS idx_messages_recipient ON messages(recipient_id,created);
CREATE INDEX IF NOT EXISTS idx_ai_user ON ai_messages(user_id,created);

CREATE TABLE IF NOT EXISTS class_invites(class_id TEXT PRIMARY KEY REFERENCES classes(id),code TEXT NOT NULL UNIQUE);
